// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: issue617.proto

package issue617

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Verify when we have to get the size of our message
// we generated the correct size method (Size/ProtoSize).
type FooSize struct {
	// Types that are valid to be assigned to TestOneof:
	//	*FooSize_Field1
	//	*FooSize_Field2
	TestOneof            isFooSize_TestOneof `protobuf_oneof:"test_oneof"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FooSize) Reset()         { *m = FooSize{} }
func (m *FooSize) String() string { return proto.CompactTextString(m) }
func (*FooSize) ProtoMessage()    {}
func (*FooSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be66a68e4f427ad, []int{0}
}
func (m *FooSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooSize.Unmarshal(m, b)
}
func (m *FooSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FooSize.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FooSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooSize.Merge(m, src)
}
func (m *FooSize) XXX_Size() int {
	return m.Size()
}
func (m *FooSize) XXX_DiscardUnknown() {
	xxx_messageInfo_FooSize.DiscardUnknown(m)
}

var xxx_messageInfo_FooSize proto.InternalMessageInfo

type isFooSize_TestOneof interface {
	isFooSize_TestOneof()
	MarshalTo([]byte) (int, error)
	Size() int
}

type FooSize_Field1 struct {
	Field1 float64 `protobuf:"fixed64,1,opt,name=Field1,oneof"`
}
type FooSize_Field2 struct {
	Field2 float32 `protobuf:"fixed32,2,opt,name=Field2,oneof"`
}

func (*FooSize_Field1) isFooSize_TestOneof() {}
func (*FooSize_Field2) isFooSize_TestOneof() {}

func (m *FooSize) GetTestOneof() isFooSize_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *FooSize) GetField1() float64 {
	if x, ok := m.GetTestOneof().(*FooSize_Field1); ok {
		return x.Field1
	}
	return 0
}

func (m *FooSize) GetField2() float32 {
	if x, ok := m.GetTestOneof().(*FooSize_Field2); ok {
		return x.Field2
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FooSize) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FooSize_Field1)(nil),
		(*FooSize_Field2)(nil),
	}
}

type FooProtoSize struct {
	// Types that are valid to be assigned to TestOneof:
	//	*FooProtoSize_Field1
	//	*FooProtoSize_Field2
	TestOneof            isFooProtoSize_TestOneof `protobuf_oneof:"test_oneof"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FooProtoSize) Reset()         { *m = FooProtoSize{} }
func (m *FooProtoSize) String() string { return proto.CompactTextString(m) }
func (*FooProtoSize) ProtoMessage()    {}
func (*FooProtoSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be66a68e4f427ad, []int{1}
}
func (m *FooProtoSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooProtoSize.Unmarshal(m, b)
}
func (m *FooProtoSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FooProtoSize.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FooProtoSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooProtoSize.Merge(m, src)
}
func (m *FooProtoSize) XXX_Size() int {
	return m.ProtoSize()
}
func (m *FooProtoSize) XXX_DiscardUnknown() {
	xxx_messageInfo_FooProtoSize.DiscardUnknown(m)
}

var xxx_messageInfo_FooProtoSize proto.InternalMessageInfo

type isFooProtoSize_TestOneof interface {
	isFooProtoSize_TestOneof()
	MarshalTo([]byte) (int, error)
	ProtoSize() int
}

type FooProtoSize_Field1 struct {
	Field1 float64 `protobuf:"fixed64,1,opt,name=Field1,oneof"`
}
type FooProtoSize_Field2 struct {
	Field2 float32 `protobuf:"fixed32,2,opt,name=Field2,oneof"`
}

func (*FooProtoSize_Field1) isFooProtoSize_TestOneof() {}
func (*FooProtoSize_Field2) isFooProtoSize_TestOneof() {}

func (m *FooProtoSize) GetTestOneof() isFooProtoSize_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *FooProtoSize) GetField1() float64 {
	if x, ok := m.GetTestOneof().(*FooProtoSize_Field1); ok {
		return x.Field1
	}
	return 0
}

func (m *FooProtoSize) GetField2() float32 {
	if x, ok := m.GetTestOneof().(*FooProtoSize_Field2); ok {
		return x.Field2
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FooProtoSize) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FooProtoSize_Field1)(nil),
		(*FooProtoSize_Field2)(nil),
	}
}

func init() {
	proto.RegisterType((*FooSize)(nil), "issue617.FooSize")
	proto.RegisterType((*FooProtoSize)(nil), "issue617.FooProtoSize")
}

func init() { proto.RegisterFile("issue617.proto", fileDescriptor_8be66a68e4f427ad) }

var fileDescriptor_8be66a68e4f427ad = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2c, 0x2e, 0x2e,
	0x4d, 0x35, 0x33, 0x34, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0xa5, 0x74,
	0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xd3, 0xf3, 0xd3, 0xf3, 0xf5,
	0xc1, 0x0a, 0x92, 0x4a, 0xd3, 0xc0, 0x3c, 0x30, 0x07, 0xcc, 0x82, 0x68, 0x54, 0x0a, 0xe4, 0x62,
	0x77, 0xcb, 0xcf, 0x0f, 0xce, 0xac, 0x4a, 0x15, 0x92, 0xe0, 0x62, 0x73, 0xcb, 0x4c, 0xcd, 0x49,
	0x31, 0x94, 0x60, 0x54, 0x60, 0xd4, 0x60, 0xf4, 0x60, 0x08, 0x82, 0xf2, 0xe1, 0x32, 0x46, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x4c, 0x70, 0x19, 0x23, 0x2b, 0x96, 0x05, 0x0b, 0xe5, 0x19, 0x9d, 0x78,
	0xb8, 0xb8, 0x4a, 0x52, 0x8b, 0x4b, 0xe2, 0xf3, 0xf3, 0x52, 0xf3, 0xd3, 0x94, 0xc2, 0xb8, 0x78,
	0xdc, 0xf2, 0xf3, 0x03, 0x40, 0xc6, 0x93, 0x6f, 0xee, 0x03, 0x0c, 0x73, 0x9d, 0x58, 0x4e, 0x3c,
	0x92, 0x63, 0x04, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xc6, 0xd5, 0xb6, 0xfa, 0x00, 0x00, 0x00,
}

func (m *FooSize) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FooSize) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FooSize) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.TestOneof != nil {
		{
			size := m.TestOneof.Size()
			i -= size
			if _, err := m.TestOneof.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *FooSize_Field1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FooSize_Field1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 8
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Field1))))
	i--
	dAtA[i] = 0x9
	return len(dAtA) - i, nil
}
func (m *FooSize_Field2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FooSize_Field2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 4
	encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Field2))))
	i--
	dAtA[i] = 0x15
	return len(dAtA) - i, nil
}
func (m *FooProtoSize) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FooProtoSize) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FooProtoSize) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.TestOneof != nil {
		{
			size := m.TestOneof.ProtoSize()
			i -= size
			if _, err := m.TestOneof.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *FooProtoSize_Field1) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FooProtoSize_Field1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 8
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Field1))))
	i--
	dAtA[i] = 0x9
	return len(dAtA) - i, nil
}
func (m *FooProtoSize_Field2) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FooProtoSize_Field2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 4
	encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Field2))))
	i--
	dAtA[i] = 0x15
	return len(dAtA) - i, nil
}
func encodeVarintIssue617(dAtA []byte, offset int, v uint64) int {
	offset -= sovIssue617(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FooSize) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TestOneof != nil {
		n += m.TestOneof.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *FooSize_Field1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 9
	return n
}
func (m *FooSize_Field2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 5
	return n
}
func (m *FooProtoSize) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TestOneof != nil {
		n += m.TestOneof.ProtoSize()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *FooProtoSize_Field1) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 9
	return n
}
func (m *FooProtoSize_Field2) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 5
	return n
}

func sovIssue617(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIssue617(x uint64) (n int) {
	return sovIssue617(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
