// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: issue580.proto

package issue580

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MyMessage_MyEnum int32

const (
	MyMessage_CASE0 MyMessage_MyEnum = 0
	MyMessage_CASE1 MyMessage_MyEnum = 1
	MyMessage_CASE2 MyMessage_MyEnum = 2
	MyMessage_CASE3 MyMessage_MyEnum = 3
	MyMessage_CASE4 MyMessage_MyEnum = 4
	MyMessage_CASE5 MyMessage_MyEnum = 5
	MyMessage_CASE6 MyMessage_MyEnum = 6
)

var MyMessage_MyEnum_name = map[int32]string{
	0: "CASE0",
	1: "CASE1",
	2: "CASE2",
	3: "CASE3",
	4: "CASE4",
	5: "CASE5",
	6: "CASE6",
}

var MyMessage_MyEnum_value = map[string]int32{
	"CASE0": 0,
	"CASE1": 1,
	"CASE2": 2,
	"CASE3": 3,
	"CASE4": 4,
	"CASE5": 5,
	"CASE6": 6,
}

func (x MyMessage_MyEnum) String() string {
	return proto.EnumName(MyMessage_MyEnum_name, int32(x))
}

func (MyMessage_MyEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2e2ba514aa42e113, []int{0, 0}
}

type MyMessage struct {
	E                    MyMessage_MyEnum `protobuf:"varint,15,opt,name=e,proto3,enum=issue580.MyMessage_MyEnum" json:"e,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MyMessage) Reset()         { *m = MyMessage{} }
func (m *MyMessage) String() string { return proto.CompactTextString(m) }
func (*MyMessage) ProtoMessage()    {}
func (*MyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2ba514aa42e113, []int{0}
}
func (m *MyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMessage.Unmarshal(m, b)
}
func (m *MyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMessage.Marshal(b, m, deterministic)
}
func (m *MyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMessage.Merge(m, src)
}
func (m *MyMessage) XXX_Size() int {
	return xxx_messageInfo_MyMessage.Size(m)
}
func (m *MyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MyMessage proto.InternalMessageInfo

func (m *MyMessage) GetE() MyMessage_MyEnum {
	if m != nil {
		return m.E
	}
	return MyMessage_CASE0
}

func init() {
	proto.RegisterEnum("issue580.MyMessage_MyEnum", MyMessage_MyEnum_name, MyMessage_MyEnum_value)
	proto.RegisterType((*MyMessage)(nil), "issue580.MyMessage")
}

func init() { proto.RegisterFile("issue580.proto", fileDescriptor_2e2ba514aa42e113) }

var fileDescriptor_2e2ba514aa42e113 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2c, 0x2e, 0x2e,
	0x4d, 0x35, 0xb5, 0x30, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x7a,
	0x18, 0xb9, 0x38, 0x7d, 0x2b, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x34, 0xb8, 0x18,
	0x53, 0x25, 0xf8, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0xa4, 0xf4, 0xe0, 0x7a, 0xe0, 0xf2, 0x7a, 0xbe,
	0x95, 0xae, 0x79, 0xa5, 0xb9, 0x41, 0x8c, 0xa9, 0x4a, 0xa1, 0x5c, 0x6c, 0x10, 0x8e, 0x10, 0x27,
	0x17, 0xab, 0xb3, 0x63, 0xb0, 0xab, 0x81, 0x00, 0x03, 0x8c, 0x69, 0x28, 0xc0, 0x08, 0x63, 0x1a,
	0x09, 0x30, 0xc1, 0x98, 0xc6, 0x02, 0xcc, 0x30, 0xa6, 0x89, 0x00, 0x0b, 0x8c, 0x69, 0x2a, 0xc0,
	0x0a, 0x63, 0x9a, 0x09, 0xb0, 0x25, 0xb1, 0x81, 0xdd, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x71, 0xea, 0x13, 0x16, 0xb1, 0x00, 0x00, 0x00,
}
