// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stdtime.proto

package stdtime

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type StdTime struct {
	T1                   *time.Time `protobuf:"bytes,1,opt,name=t1,proto3,stdtime" json:"t1,omitempty"`
	T2                   time.Time  `protobuf:"bytes,2,opt,name=t2,proto3,stdtime" json:"t2"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StdTime) Reset()         { *m = StdTime{} }
func (m *StdTime) String() string { return proto.CompactTextString(m) }
func (*StdTime) ProtoMessage()    {}
func (*StdTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_0baf59d78c85f426, []int{0}
}
func (m *StdTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StdTime.Unmarshal(m, b)
}
func (m *StdTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StdTime.Marshal(b, m, deterministic)
}
func (m *StdTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StdTime.Merge(m, src)
}
func (m *StdTime) XXX_Size() int {
	return xxx_messageInfo_StdTime.Size(m)
}
func (m *StdTime) XXX_DiscardUnknown() {
	xxx_messageInfo_StdTime.DiscardUnknown(m)
}

var xxx_messageInfo_StdTime proto.InternalMessageInfo

func (m *StdTime) GetT1() *time.Time {
	if m != nil {
		return m.T1
	}
	return nil
}

func (m *StdTime) GetT2() time.Time {
	if m != nil {
		return m.T2
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*StdTime)(nil), "stdtime.StdTime")
}

func init() { proto.RegisterFile("stdtime.proto", fileDescriptor_0baf59d78c85f426) }

var fileDescriptor_0baf59d78c85f426 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x49, 0x29,
	0xc9, 0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0xa5, 0x74, 0xd3,
	0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xd3, 0xf3, 0xd3, 0xf3, 0xf5, 0xc1,
	0xf2, 0x49, 0xa5, 0x69, 0x60, 0x1e, 0x98, 0x03, 0x66, 0x41, 0xf4, 0x49, 0xc9, 0xa7, 0xe7, 0xe7,
	0xa7, 0xe7, 0xa4, 0x22, 0x54, 0x81, 0x0c, 0x29, 0x2e, 0x49, 0xcc, 0x2d, 0x80, 0x28, 0x50, 0x2a,
	0xe4, 0x62, 0x0f, 0x2e, 0x49, 0x09, 0xc9, 0xcc, 0x4d, 0x15, 0x32, 0xe0, 0x62, 0x2a, 0x31, 0x94,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0x68, 0xd4, 0x83, 0x69, 0xd4, 0x0b, 0x81,
	0x69, 0x74, 0x62, 0x99, 0x70, 0x5f, 0x9e, 0x31, 0x88, 0xa9, 0xc4, 0x50, 0xc8, 0x84, 0x8b, 0xa9,
	0xc4, 0x48, 0x82, 0x89, 0xa0, 0x0e, 0x8e, 0x13, 0xf7, 0xe4, 0x19, 0xa0, 0xba, 0x8c, 0x9c, 0x78,
	0x4e, 0x3c, 0x92, 0x63, 0xb8, 0xf0, 0x48, 0x8e, 0xe1, 0xc1, 0x23, 0x39, 0xc6, 0x24, 0x36, 0xb0,
	0x7a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0xe4, 0xa4, 0xc8, 0xf1, 0x00, 0x00, 0x00,
}

func (m *StdTime) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.T1 != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.T1)
		n += 1 + l + sovStdtime(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.T2)
	n += 1 + l + sovStdtime(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovStdtime(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozStdtime(x uint64) (n int) {
	return sovStdtime(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
