// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: issue541.proto

package issue541

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type OuterMessage struct {
	Fieldone string        `protobuf:"bytes,1,opt,name=fieldone,proto3" json:"fieldone,omitempty"`
	Inner    *InnerMessage `protobuf:"bytes,2,opt,name=inner,proto3" json:"inner,omitempty"`
	// Types that are valid to be assigned to OneOfFoo:
	//	*OuterMessage_FooOne
	//	*OuterMessage_FooTwo
	OneOfFoo             isOuterMessage_OneOfFoo `protobuf_oneof:"OneOfFoo"`
	BazListValue         *types.ListValue        `protobuf:"bytes,5,opt,name=BazListValue,proto3" json:"BazListValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *OuterMessage) Reset()         { *m = OuterMessage{} }
func (m *OuterMessage) String() string { return proto.CompactTextString(m) }
func (*OuterMessage) ProtoMessage()    {}
func (*OuterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffca6c10fbf86501, []int{0}
}
func (m *OuterMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OuterMessage.Unmarshal(m, b)
}
func (m *OuterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OuterMessage.Marshal(b, m, deterministic)
}
func (m *OuterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OuterMessage.Merge(m, src)
}
func (m *OuterMessage) XXX_Size() int {
	return xxx_messageInfo_OuterMessage.Size(m)
}
func (m *OuterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OuterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OuterMessage proto.InternalMessageInfo

type isOuterMessage_OneOfFoo interface {
	isOuterMessage_OneOfFoo()
}

type OuterMessage_FooOne struct {
	FooOne int64 `protobuf:"varint,3,opt,name=fooOne,proto3,oneof"`
}
type OuterMessage_FooTwo struct {
	FooTwo int32 `protobuf:"varint,4,opt,name=fooTwo,proto3,oneof"`
}

func (*OuterMessage_FooOne) isOuterMessage_OneOfFoo() {}
func (*OuterMessage_FooTwo) isOuterMessage_OneOfFoo() {}

func (m *OuterMessage) GetOneOfFoo() isOuterMessage_OneOfFoo {
	if m != nil {
		return m.OneOfFoo
	}
	return nil
}

func (m *OuterMessage) GetFieldone() string {
	if m != nil {
		return m.Fieldone
	}
	return ""
}

func (m *OuterMessage) GetInner() *InnerMessage {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *OuterMessage) GetFooOne() int64 {
	if x, ok := m.GetOneOfFoo().(*OuterMessage_FooOne); ok {
		return x.FooOne
	}
	return 0
}

func (m *OuterMessage) GetFooTwo() int32 {
	if x, ok := m.GetOneOfFoo().(*OuterMessage_FooTwo); ok {
		return x.FooTwo
	}
	return 0
}

func (m *OuterMessage) GetBazListValue() *types.ListValue {
	if m != nil {
		return m.BazListValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*OuterMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _OuterMessage_OneofMarshaler, _OuterMessage_OneofUnmarshaler, _OuterMessage_OneofSizer, []interface{}{
		(*OuterMessage_FooOne)(nil),
		(*OuterMessage_FooTwo)(nil),
	}
}

func _OuterMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*OuterMessage)
	// OneOfFoo
	switch x := m.OneOfFoo.(type) {
	case *OuterMessage_FooOne:
		_ = b.EncodeVarint(3<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.FooOne))
	case *OuterMessage_FooTwo:
		_ = b.EncodeVarint(4<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.FooTwo))
	case nil:
	default:
		return fmt.Errorf("OuterMessage.OneOfFoo has unexpected type %T", x)
	}
	return nil
}

func _OuterMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*OuterMessage)
	switch tag {
	case 3: // OneOfFoo.fooOne
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneOfFoo = &OuterMessage_FooOne{int64(x)}
		return true, err
	case 4: // OneOfFoo.fooTwo
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneOfFoo = &OuterMessage_FooTwo{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _OuterMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*OuterMessage)
	// OneOfFoo
	switch x := m.OneOfFoo.(type) {
	case *OuterMessage_FooOne:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.FooOne))
	case *OuterMessage_FooTwo:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.FooTwo))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type InnerMessage struct {
	Fieldtwo             string   `protobuf:"bytes,1,opt,name=fieldtwo,proto3" json:"fieldtwo,omitempty"`
	Fieldthree           string   `protobuf:"bytes,2,opt,name=fieldthree,proto3" json:"fieldthree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerMessage) Reset()         { *m = InnerMessage{} }
func (m *InnerMessage) String() string { return proto.CompactTextString(m) }
func (*InnerMessage) ProtoMessage()    {}
func (*InnerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffca6c10fbf86501, []int{1}
}
func (m *InnerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerMessage.Unmarshal(m, b)
}
func (m *InnerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerMessage.Marshal(b, m, deterministic)
}
func (m *InnerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerMessage.Merge(m, src)
}
func (m *InnerMessage) XXX_Size() int {
	return xxx_messageInfo_InnerMessage.Size(m)
}
func (m *InnerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InnerMessage proto.InternalMessageInfo

func (m *InnerMessage) GetFieldtwo() string {
	if m != nil {
		return m.Fieldtwo
	}
	return ""
}

func (m *InnerMessage) GetFieldthree() string {
	if m != nil {
		return m.Fieldthree
	}
	return ""
}

func init() {
	proto.RegisterType((*OuterMessage)(nil), "issue541.OuterMessage")
	proto.RegisterType((*InnerMessage)(nil), "issue541.InnerMessage")
}

func init() { proto.RegisterFile("issue541.proto", fileDescriptor_ffca6c10fbf86501) }

var fileDescriptor_ffca6c10fbf86501 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0x5d, 0x6b, 0x4a, 0x3a, 0x06, 0x0f, 0x7b, 0x90, 0x25, 0x88, 0x84, 0x9e, 0x72, 0xd0,
	0x2d, 0xfe, 0xbb, 0x7a, 0xe8, 0x41, 0x54, 0x94, 0x40, 0x28, 0xde, 0x93, 0x3a, 0xd9, 0x06, 0x62,
	0x46, 0xb2, 0xbb, 0x04, 0x7c, 0x52, 0x1f, 0x47, 0xdc, 0x4d, 0xd3, 0xf6, 0x36, 0xbf, 0x99, 0x6f,
	0x77, 0xe6, 0x83, 0xb3, 0x5a, 0x6b, 0x8b, 0x0f, 0xf7, 0x37, 0xf2, 0xbb, 0x23, 0x43, 0x3c, 0xdc,
	0xe6, 0xf8, 0x5a, 0xd5, 0x66, 0x63, 0x4b, 0xb9, 0xa6, 0xaf, 0x85, 0x22, 0x45, 0x0b, 0x07, 0x94,
	0xb6, 0x72, 0xc9, 0x05, 0x57, 0xf9, 0x87, 0xf1, 0x85, 0x22, 0x52, 0x0d, 0xee, 0x28, 0x6d, 0x3a,
	0xbb, 0x36, 0x7e, 0x3a, 0xff, 0x65, 0x10, 0x65, 0xd6, 0x60, 0xf7, 0x8e, 0x5a, 0x17, 0x0a, 0x79,
	0x0c, 0x61, 0x55, 0x63, 0xf3, 0x49, 0x2d, 0x0a, 0x96, 0xb0, 0x74, 0x96, 0x8f, 0x99, 0x5f, 0x41,
	0x50, 0xb7, 0x2d, 0x76, 0xe2, 0x38, 0x61, 0xe9, 0xe9, 0xed, 0xb9, 0x1c, 0x6f, 0x7c, 0xf9, 0x6f,
	0x0f, 0x5f, 0xe4, 0x1e, 0xe2, 0x02, 0xa6, 0x15, 0x51, 0xd6, 0xa2, 0x98, 0x24, 0x2c, 0x9d, 0x3c,
	0x1f, 0xe5, 0x43, 0x1e, 0x26, 0xab, 0x9e, 0xc4, 0x49, 0xc2, 0xd2, 0x60, 0x98, 0xac, 0x7a, 0xe2,
	0x8f, 0x10, 0x2d, 0x8b, 0x9f, 0xb7, 0x5a, 0x9b, 0x8f, 0xa2, 0xb1, 0x28, 0x02, 0xb7, 0x28, 0x96,
	0xde, 0x41, 0x6e, 0x1d, 0xe4, 0x48, 0xe4, 0x07, 0xfc, 0x12, 0x20, 0xcc, 0x5a, 0xcc, 0xaa, 0x27,
	0xa2, 0xf9, 0x2b, 0x44, 0xfb, 0x67, 0x8d, 0x66, 0xa6, 0xa7, 0x03, 0x33, 0xd3, 0x13, 0xbf, 0x04,
	0xf0, 0xf5, 0xa6, 0x43, 0x74, 0x7a, 0xb3, 0x7c, 0xaf, 0x53, 0x4e, 0xdd, 0xe6, 0xbb, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe9, 0xc9, 0xb9, 0x5b, 0x96, 0x01, 0x00, 0x00,
}
